In [13]:
import numpy as np
import torch
import torch.nn

In [14]:
a = torch.tensor([[[[1.,1],[1,1]],[[0,1],[1,0]],[[0,0],[0,1]],[[1,1],[0,0]]],
                  [[[2.,2],[0,0]],[[2,0],[1,1]],[[1,0],[0,2]],[[2,1],[1,0]]],
                  [[[3.,1],[2,2]],[[3,0],[0,2]],[[2,3],[1,2]],[[3,3],[2,1]]]])
c = a.clone()
a.shape, c.reshape(-1)

(torch.Size([3, 4, 2, 2]),
 tensor([1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 2., 2.,
         0., 0., 2., 0., 1., 1., 1., 0., 0., 2., 2., 1., 1., 0., 3., 1., 2., 2.,
         3., 0., 0., 2., 2., 3., 1., 2., 3., 3., 2., 1.]))

In [15]:
a.shape, a

(torch.Size([3, 4, 2, 2]),
 tensor([[[[1., 1.],
           [1., 1.]],
 
          [[0., 1.],
           [1., 0.]],
 
          [[0., 0.],
           [0., 1.]],
 
          [[1., 1.],
           [0., 0.]]],
 
 
         [[[2., 2.],
           [0., 0.]],
 
          [[2., 0.],
           [1., 1.]],
 
          [[1., 0.],
           [0., 2.]],
 
          [[2., 1.],
           [1., 0.]]],
 
 
         [[[3., 1.],
           [2., 2.]],
 
          [[3., 0.],
           [0., 2.]],
 
          [[2., 3.],
           [1., 2.]],
 
          [[3., 3.],
           [2., 1.]]]]))

In [16]:
gn = torch.nn.GroupNorm(num_groups=2, num_channels=4, affine=True)
m = gn(a)
m.shape, m

(torch.Size([3, 4, 2, 2]),
 tensor([[[[ 5.7733e-01,  5.7733e-01],
           [ 5.7733e-01,  5.7733e-01]],
 
          [[-1.7320e+00,  5.7733e-01],
           [ 5.7733e-01, -1.7320e+00]],
 
          [[-7.7458e-01, -7.7458e-01],
           [-7.7458e-01,  1.2910e+00]],
 
          [[ 1.2910e+00,  1.2910e+00],
           [-7.7458e-01, -7.7458e-01]]],
 
 
         [[[ 1.1547e+00,  1.1547e+00],
           [-1.1547e+00, -1.1547e+00]],
 
          [[ 1.1547e+00, -1.1547e+00],
           [ 1.1921e-07,  1.1921e-07]],
 
          [[ 1.6013e-01, -1.1209e+00],
           [-1.1209e+00,  1.4411e+00]],
 
          [[ 1.4411e+00,  1.6013e-01],
           [ 1.6013e-01, -1.1209e+00]]],
 
 
         [[[ 1.2376e+00, -5.6254e-01],
           [ 3.3753e-01,  3.3753e-01]],
 
          [[ 1.2376e+00, -1.4626e+00],
           [-1.4626e+00,  3.3753e-01]],
 
          [[-1.6013e-01,  1.1209e+00],
           [-1.4411e+00, -1.6013e-01]],
 
          [[ 1.1209e+00,  1.1209e+00],
           [-1.6013e-01, -1.4411e+00]

In [26]:
m.reshape(-1)

tensor([ 5.7733e-01,  5.7733e-01,  5.7733e-01,  5.7733e-01, -1.7320e+00,
         5.7733e-01,  5.7733e-01, -1.7320e+00, -7.7458e-01, -7.7458e-01,
        -7.7458e-01,  1.2910e+00,  1.2910e+00,  1.2910e+00, -7.7458e-01,
        -7.7458e-01,  1.1547e+00,  1.1547e+00, -1.1547e+00, -1.1547e+00,
         1.1547e+00, -1.1547e+00,  1.1921e-07,  1.1921e-07,  1.6013e-01,
        -1.1209e+00, -1.1209e+00,  1.4411e+00,  1.4411e+00,  1.6013e-01,
         1.6013e-01, -1.1209e+00,  1.2376e+00, -5.6254e-01,  3.3753e-01,
         3.3753e-01,  1.2376e+00, -1.4626e+00, -1.4626e+00,  3.3753e-01,
        -1.6013e-01,  1.1209e+00, -1.4411e+00, -1.6013e-01,  1.1209e+00,
         1.1209e+00, -1.6013e-01, -1.4411e+00],
       grad_fn=<ReshapeAliasBackward0>)

In [17]:
tmp = a[0, :2, :].clone()
(tmp - tmp.mean()) / tmp.std(correction=0)

tensor([[[ 0.5774,  0.5774],
         [ 0.5774,  0.5774]],

        [[-1.7321,  0.5774],
         [ 0.5774, -1.7321]]])

In [18]:
b = np.array([1,1,1,1,1,1,0,0])

In [19]:
(b - b.mean()) / b.std()

array([ 0.57735027,  0.57735027,  0.57735027,  0.57735027,  0.57735027,
        0.57735027, -1.73205081, -1.73205081])

In [20]:
tmp.mean(dim=(0,2))

tensor([0.7500, 0.7500])

In [21]:
(1 - 0.75) / 1.433012

0.17445771563671483

In [22]:
for param in gn.parameters():
    print(param.shape, param.name, param)

torch.Size([4]) None Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
torch.Size([4]) None Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)


In [25]:
gn2 = torch.nn.GroupNorm(num_groups=4, num_channels=24, affine=True)
for param in gn2.parameters():
    print(param.shape, param.name, param)

torch.Size([24]) None Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.], requires_grad=True)
torch.Size([24]) None Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)
