In [52]:
import numpy as np
import torch
import torch.nn

In [152]:
a = torch.tensor([[[[1.,1],[1,1]],[[0,1],[1,0]],[[0,0],[0,1]],[[1,1],[0,0]]],
                  [[[2.,2],[0,0]],[[2,0],[1,1]],[[1,0],[0,2]],[[2,1],[1,0]]],
                  [[[3.,1],[2,2]],[[3,0],[0,2]],[[2,3],[1,2]],[[3,3],[2,1]]]])
c = a.clone()
a.shape, c.reshape(-1)

(torch.Size([3, 4, 2, 2]),
 tensor([1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 2., 2.,
         0., 0., 2., 0., 1., 1., 1., 0., 0., 2., 2., 1., 1., 0., 3., 1., 2., 2.,
         3., 0., 0., 2., 2., 3., 1., 2., 3., 3., 2., 1.]))

In [80]:
a.shape, a

(torch.Size([3, 4, 2, 2]),
 tensor([[[[1., 1.],
           [1., 1.]],
 
          [[0., 1.],
           [1., 0.]],
 
          [[0., 0.],
           [0., 1.]],
 
          [[1., 1.],
           [0., 0.]]],
 
 
         [[[2., 2.],
           [0., 0.]],
 
          [[2., 0.],
           [1., 1.]],
 
          [[1., 0.],
           [0., 2.]],
 
          [[2., 1.],
           [1., 0.]]],
 
 
         [[[3., 1.],
           [2., 2.]],
 
          [[3., 0.],
           [0., 2.]],
 
          [[2., 3.],
           [1., 2.]],
 
          [[3., 3.],
           [2., 1.]]]]))

In [153]:
gn = torch.nn.GroupNorm(num_groups=2, num_channels=4, affine=True)
m = gn(a)
m.shape, m

(torch.Size([3, 4, 2, 2]),
 tensor([[[[ 5.7733e-01,  5.7733e-01],
           [ 5.7733e-01,  5.7733e-01]],
 
          [[-1.7320e+00,  5.7733e-01],
           [ 5.7733e-01, -1.7320e+00]],
 
          [[-7.7458e-01, -7.7458e-01],
           [-7.7458e-01,  1.2910e+00]],
 
          [[ 1.2910e+00,  1.2910e+00],
           [-7.7458e-01, -7.7458e-01]]],
 
 
         [[[ 1.1547e+00,  1.1547e+00],
           [-1.1547e+00, -1.1547e+00]],
 
          [[ 1.1547e+00, -1.1547e+00],
           [ 1.1921e-07,  1.1921e-07]],
 
          [[ 1.6013e-01, -1.1209e+00],
           [-1.1209e+00,  1.4411e+00]],
 
          [[ 1.4411e+00,  1.6013e-01],
           [ 1.6013e-01, -1.1209e+00]]],
 
 
         [[[ 1.2376e+00, -5.6254e-01],
           [ 3.3753e-01,  3.3753e-01]],
 
          [[ 1.2376e+00, -1.4626e+00],
           [-1.4626e+00,  3.3753e-01]],
 
          [[-1.6013e-01,  1.1209e+00],
           [-1.4411e+00, -1.6013e-01]],
 
          [[ 1.1209e+00,  1.1209e+00],
           [-1.6013e-01, -1.4411e+00]

In [129]:
tmp = a[0, :2, :].clone()
(tmp - tmp.mean()) / tmp.std(correction=0)

tensor([[[ 0.5774,  0.5774],
         [ 0.5774,  0.5774]],

        [[-1.7321,  0.5774],
         [ 0.5774, -1.7321]]])

In [112]:
b = np.array([1,1,1,1,1,1,0,0])

In [130]:
(b - b.mean()) / b.std()

array([ 0.57735027,  0.57735027,  0.57735027,  0.57735027,  0.57735027,
        0.57735027, -1.73205081, -1.73205081])

In [131]:
tmp.mean(dim=(0,2))

tensor([0.7500, 0.7500])

In [134]:
(1 - 0.75) / 1.433012

0.17445771563671483

In [157]:
for param in gn.parameters():
    print(param.shape)

torch.Size([4])
torch.Size([4])
