In [3]:
import faiss
import numpy as np

In [5]:
(faiss.__version__, np.__version__)

('1.7.4', '1.26.2')

# Getting some data

In [8]:
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.
(xq.shape, xq.dtype)

((10000, 64), dtype('float32'))

# Building an index and adding the vectors to it

In [9]:
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

True
100000


# Searching

In [10]:
k = 4                          # we want to see 4 nearest neighbors

## sanity check

In [14]:
D, I = index.search(xb[:5], k) # sanity check
print(I.shape, D.shape)
print(I)
print(D)

(5, 4) (5, 4)
[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751738 7.2076297 7.2511625]
 [0.        6.3235645 6.684581  6.799946 ]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.5279875 7.6628466]
 [0.        6.7638035 7.2951202 7.368815 ]]
