In [39]:
import numpy as np
import torch
import torch.nn

In [45]:
torch.set_printoptions(precision=8, sci_mode=False)

In [28]:
a = torch.tensor([[[[1.,1],[1,1]],[[0,1],[1,0]],[[0,0],[0,1]],[[1,1],[0,0]]],
                  [[[2.,2],[0,0]],[[2,0],[1,1]],[[1,0],[0,2]],[[2,1],[1,0]]],
                  [[[3.,1],[2,2]],[[3,0],[0,2]],[[2,3],[1,2]],[[3,3],[2,1]]]])
a.shape, a.reshape(-1)

(torch.Size([3, 4, 2, 2]),
 tensor([1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 2., 2.,
         0., 0., 2., 0., 1., 1., 1., 0., 0., 2., 2., 1., 1., 0., 3., 1., 2., 2.,
         3., 0., 0., 2., 2., 3., 1., 2., 3., 3., 2., 1.]))

In [48]:
gn = torch.nn.GroupNorm(num_groups=4, num_channels=4, affine=True)
m = gn(a)
m.shape, m

(torch.Size([3, 4, 2, 2]),
 tensor([[[[ 0.00000000,  0.00000000],
           [ 0.00000000,  0.00000000]],
 
          [[-0.99997997,  0.99997997],
           [ 0.99997997, -0.99997997]],
 
          [[-0.57733488, -0.57733488],
           [-0.57733488,  1.73200464]],
 
          [[ 0.99998009,  0.99998009],
           [-0.99997997, -0.99997997]]],
 
 
         [[[ 0.99999511,  0.99999511],
           [-0.99999499, -0.99999499]],
 
          [[ 1.41419947, -1.41419947],
           [ 0.00000000,  0.00000000]],
 
          [[ 0.30150914, -0.90452743],
           [-0.90452743,  1.50754571]],
 
          [[ 1.41419947,  0.00000000],
           [ 0.00000000, -1.41419947]]],
 
 
         [[[ 1.41419959, -1.41419947],
           [ 0.00000000,  0.00000000]],
 
          [[ 1.34714675, -0.96224761],
           [-0.96224761,  0.57734859]],
 
          [[ 0.00000000,  1.41419959],
           [-1.41419947,  0.00000000]],
 
          [[ 0.90452743,  0.90452743],
           [-0.30150914, -1.50754571]

In [49]:
m.reshape(-1)

tensor([ 0.00000000,  0.00000000,  0.00000000,  0.00000000, -0.99997997,
         0.99997997,  0.99997997, -0.99997997, -0.57733488, -0.57733488,
        -0.57733488,  1.73200464,  0.99998009,  0.99998009, -0.99997997,
        -0.99997997,  0.99999511,  0.99999511, -0.99999499, -0.99999499,
         1.41419947, -1.41419947,  0.00000000,  0.00000000,  0.30150914,
        -0.90452743, -0.90452743,  1.50754571,  1.41419947,  0.00000000,
         0.00000000, -1.41419947,  1.41419959, -1.41419947,  0.00000000,
         0.00000000,  1.34714675, -0.96224761, -0.96224761,  0.57734859,
         0.00000000,  1.41419959, -1.41419947,  0.00000000,  0.90452743,
         0.90452743, -0.30150914, -1.50754571],
       grad_fn=<ReshapeAliasBackward0>)

In [32]:
tmp = a[0, :2, :].clone()
(tmp - tmp.mean()) / tmp.std(correction=0)

tensor([[[ 0.5774,  0.5774],
         [ 0.5774,  0.5774]],

        [[-1.7321,  0.5774],
         [ 0.5774, -1.7321]]])

In [33]:
b = np.array([1,1,1,1,1,1,0,0])

In [34]:
(b - b.mean()) / b.std()

array([ 0.57735027,  0.57735027,  0.57735027,  0.57735027,  0.57735027,
        0.57735027, -1.73205081, -1.73205081])

In [35]:
tmp.mean(dim=(0,2))

tensor([0.7500, 0.7500])

In [36]:
(1 - 0.75) / 1.433012

0.17445771563671483

In [37]:
for param in gn.parameters():
    print(param.shape, param.name, param)

torch.Size([4]) None Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
torch.Size([4]) None Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)


In [38]:
gn2 = torch.nn.GroupNorm(num_groups=4, num_channels=24, affine=True)
for param in gn2.parameters():
    print(param.shape, param.name, param)

torch.Size([24]) None Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.], requires_grad=True)
torch.Size([24]) None Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)


In [51]:
a = torch.randn(4,6,3,5)
a.shape, a.reshape(-1)

(torch.Size([4, 6, 3, 5]),
 tensor([ 0.84387422,  0.37547702, -0.99206406, -0.20603140, -0.20786867,
         -0.87118918,  1.11870074, -1.28895068, -0.13744405,  1.05048180,
          1.19548523, -0.02178703,  1.15484929, -0.03947303, -0.68050402,
          1.58700252, -0.59433615,  0.91509616,  1.32786167, -1.69399869,
         -2.35835338,  0.72684515, -0.75297421,  1.29682600,  1.03896415,
         -1.10807753,  0.65309709, -1.16990268,  0.70982718,  1.08366930,
          0.81680143,  0.31865793,  0.24858120,  0.26446846,  0.82651758,
         -0.94556022, -0.69861805, -0.83773184,  1.15827417, -1.08496702,
         -1.77108574, -0.57323325,  0.20869491, -0.69128221,  2.18944359,
          1.62454164, -0.32228658,  0.50739175, -1.22718811, -0.39650065,
          0.49119896, -0.40224800, -0.28312895,  0.63294441, -1.58948362,
          0.38457578,  0.96528256, -0.97960132, -1.22510576, -0.46788737,
         -0.28448573,  0.17722097,  0.91297513, -1.17173707, -0.87876439,
          0

In [53]:
gn = torch.nn.GroupNorm(num_groups=3, num_channels=6, affine=True)
m = gn(a)
m.shape, m.reshape(-1)

(torch.Size([4, 6, 3, 5]),
 tensor([ 0.72039741,  0.26769370, -1.05402851, -0.29433149, -0.29610720,
         -0.93720341,  0.98601598, -1.34096801, -0.22804216,  0.92008275,
          1.06022787, -0.11626018,  1.02095342, -0.13335361, -0.75290710,
          1.43862748, -0.66962624,  0.78923315,  1.18816900, -1.73244512,
         -2.37454081,  0.60728937, -0.82294923,  1.15817320,  0.90895098,
         -1.16615498,  0.53601223, -1.22590876,  0.59084159,  0.95215827,
          0.96994394,  0.44020078,  0.36567873,  0.38257378,  0.98027647,
         -0.90421283, -0.64160591, -0.78954434,  1.33307791, -1.05246282,
         -1.78210545, -0.50826734,  0.32326227, -0.63380474,  2.42965937,
          1.82892299, -0.24140194,  0.64090693, -1.20370579, -0.32032380,
          0.62368691, -0.32643571, -0.19976038,  0.77442396, -1.58898342,
          0.51030010,  1.12784398, -0.94041336, -1.20149136, -0.39623892,
         -0.21167088,  0.26793343,  1.03220832, -1.13331568, -0.82898617,
          0